FROM redmine:latest

RUN apt-get update && \
    apt-get install -y wget mariadb-client && \
    mkdir -p /home/redmine/.mysql && \
    wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" \
         --output-document=/home/redmine/.mysql/root.crt && \
    chmod 0600 /home/redmine/.mysql/root.crt
