---
- name: Prepare servers for deployment
  hosts: all
  become: true
  roles:
    - geerlingguy.pip
  vars_files:
    - group_vars/webservers/vault.yml

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Docker Engine
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Install Docker Python library
      ansible.builtin.command:
        cmd: "pip3 install docker"
        creates: /usr/local/bin/docker
    - name: Update the community.docker collection
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install community.docker --upgrade
