---
- name: Installing and starting DataDog
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/webservers/vault.yml
  tasks:
    - name: Install agent DataDog
      shell: |
        DD_API_KEY={{ DD_API_KEY }} \
        DD_SITE={{ DD_SITE }} \
        bash -c "$(curl -L https://install.datadoghq.com/scripts/install_script_agent7.sh)"
      args:
        creates: /etc/datadog-agent/datadog.yaml

    - name: Starting agent DataDog
      service:
        name: datadog-agent
        state: started
        enabled: yes

    - name: Configuring http_check for monitoring
      copy:
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
        content: |
          init_config:

          instances:
            - name: "App Health Check"
              url: "http://hexletlab.adizit.kz:8080/health"
              timeout: 5
              check_interval: 30
              thresholds:
                critical: 1
                warning: 2
              tags:
                - "env:production"
                - "service:app_health"

    - name: Restarting DataDog
      service:
        name: datadog-agent
        state: restarted
